backend:
  replicaCount: 1
  image:
    tag: main-ff1caeae-63
    repository: mehdibenzaied/flight-delay-backend
frontend:
  replicaCount: 1
  image:
    tag: main-ff1caeae-63
    repository: mehdibenzaied/flight-delay-frontend
  service:
    type: NodePort
    nodePort: 30080
analytics:
  replicaCount: 1
  service:
    type: NodePort
    nodePort: 30085
  image:
    repository: mehdibenzaied/flight-delay-backend
    tag: main-ff1caeae-63
ingress:
  enabled: false
